// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type CouponReservations struct {
	ID          int32        `json:"id"`
	UserID      int32        `json:"user_id"`
	ReservedAt  time.Time    `json:"reserved_at"`
	IsProcessed sql.NullBool `json:"is_processed"`
}

type Coupons struct {
	ID         int32         `json:"id"`
	Code       string        `json:"code"`
	Discount   string        `json:"discount"`
	ExpiryDate time.Time     `json:"expiry_date"`
	IsUsed     bool          `json:"is_used"`
	UserID     sql.NullInt32 `json:"user_id"`
	CreatedAt  time.Time     `json:"created_at"`
}

type Users struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
